//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// PerpsSimple
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const PerpsABI = [
{
    type: 'constructor',
    inputs: [
    {
        name: '_minimumPriceIncrement',
        internalType: 'uint256',
        type: 'uint256',
    },
    ],
    stateMutability: 'nonpayable',
},
{
    type: 'error',
    inputs: [{ name: 'target', internalType: 'address', type: 'address' }],
    name: 'AddressEmptyCode',
},
{
    type: 'error',
    inputs: [
    { name: 'implementation', internalType: 'address', type: 'address' },
    ],
    name: 'ERC1967InvalidImplementation',
},
{ type: 'error', inputs: [], name: 'ERC1967NonPayable' },
{
    type: 'error',
    inputs: [
    { name: 'spender', internalType: 'address', type: 'address' },
    { name: 'allowance', internalType: 'uint256', type: 'uint256' },
    { name: 'needed', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'ERC20InsufficientAllowance',
},
{
    type: 'error',
    inputs: [
    { name: 'sender', internalType: 'address', type: 'address' },
    { name: 'balance', internalType: 'uint256', type: 'uint256' },
    { name: 'needed', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'ERC20InsufficientBalance',
},
{
    type: 'error',
    inputs: [{ name: 'approver', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidApprover',
},
{
    type: 'error',
    inputs: [{ name: 'receiver', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidReceiver',
},
{
    type: 'error',
    inputs: [{ name: 'sender', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidSender',
},
{
    type: 'error',
    inputs: [{ name: 'spender', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidSpender',
},
{ type: 'error', inputs: [], name: 'FailedCall' },
{ type: 'error', inputs: [], name: 'InsufficientCollateral' },
{ type: 'error', inputs: [], name: 'InsufficientMargin' },
{ type: 'error', inputs: [], name: 'InsufficientReservePool' },
{ type: 'error', inputs: [], name: 'InvalidInitialization' },
{ type: 'error', inputs: [], name: 'InvalidMarginPercent' },
{ type: 'error', inputs: [], name: 'InvalidOracle' },
{ type: 'error', inputs: [], name: 'InvalidPrice' },
{ type: 'error', inputs: [], name: 'InvalidSize' },
{ type: 'error', inputs: [], name: 'MaxOrdersPerParticipantReached' },
{ type: 'error', inputs: [], name: 'NoPosition' },
{ type: 'error', inputs: [], name: 'NotInitializing' },
{ type: 'error', inputs: [], name: 'NotLiquidatable' },
{ type: 'error', inputs: [], name: 'OracleStale' },
{ type: 'error', inputs: [], name: 'OrderNotBelongToSender' },
{
    type: 'error',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'OwnableInvalidOwner',
},
{
    type: 'error',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
},
{
    type: 'error',
    inputs: [{ name: 'token', internalType: 'address', type: 'address' }],
    name: 'SafeERC20FailedOperation',
},
{ type: 'error', inputs: [], name: 'UUPSUnauthorizedCallContext' },
{
    type: 'error',
    inputs: [{ name: 'slot', internalType: 'bytes32', type: 'bytes32' }],
    name: 'UUPSUnsupportedProxiableUUID',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    ],
    name: 'Approval',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    { name: 'user', internalType: 'address', type: 'address', indexed: true },
    {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    ],
    name: 'CollateralAdded',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    { name: 'user', internalType: 'address', type: 'address', indexed: true },
    {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    ],
    name: 'CollateralRemoved',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'version',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
    },
    ],
    name: 'Initialized',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'newLiquidationFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    ],
    name: 'LiquidationFeeUpdated',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'newMaintenanceMarginPercent',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
    },
    ],
    name: 'MaintenanceMarginPercentUpdated',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'newMarginPercent',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
    },
    ],
    name: 'MarginPercentUpdated',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'orderId',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
    },
    {
        name: 'participant',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    ],
    name: 'OrderCancelled',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'orderId',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
    },
    {
        name: 'participant',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    {
        name: 'price',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    {
        name: 'quantity',
        internalType: 'int256',
        type: 'int256',
        indexed: false,
    },
    ],
    name: 'OrderCreated',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'newFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    ],
    name: 'OrderFeeUpdated',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'orderId',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
    },
    {
        name: 'participant',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    ],
    name: 'OrderFilled',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'makerOrderId',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
    },
    {
        name: 'buyer',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    {
        name: 'seller',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    {
        name: 'price',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    {
        name: 'quantity',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    ],
    name: 'OrderMatched',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'orderId',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
    },
    {
        name: 'participant',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    {
        name: 'newQuantity',
        internalType: 'int256',
        type: 'int256',
        indexed: false,
    },
    ],
    name: 'OrderUpdated',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    ],
    name: 'OwnershipTransferred',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    { name: 'user', internalType: 'address', type: 'address', indexed: true },
    {
        name: 'quantityClosed',
        internalType: 'int256',
        type: 'int256',
        indexed: false,
    },
    { name: 'pnl', internalType: 'int256', type: 'int256', indexed: false },
    ],
    name: 'PositionClosed',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    { name: 'user', internalType: 'address', type: 'address', indexed: true },
    {
        name: 'liquidator',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    {
        name: 'positionSize',
        internalType: 'int256',
        type: 'int256',
        indexed: false,
    },
    { name: 'pnl', internalType: 'int256', type: 'int256', indexed: false },
    {
        name: 'liquidatorFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    ],
    name: 'PositionLiquidated',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    { name: 'user', internalType: 'address', type: 'address', indexed: true },
    {
        name: 'tradePrice',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    {
        name: 'quantity',
        internalType: 'int256',
        type: 'int256',
        indexed: false,
    },
    {
        name: 'netQuantityAfter',
        internalType: 'int256',
        type: 'int256',
        indexed: false,
    },
    {
        name: 'aggregatedEntryPriceAfter',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    ],
    name: 'PositionTrade',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    { name: 'from', internalType: 'address', type: 'address', indexed: true },
    { name: 'to', internalType: 'address', type: 'address', indexed: true },
    {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    ],
    name: 'Transfer',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'implementation',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    ],
    name: 'Upgraded',
},
{
    type: 'function',
    inputs: [],
    name: 'MAX_ORDERS_PER_PARTICIPANT',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'QUANTITY_DECIMALS',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'UPGRADE_INTERFACE_VERSION',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_amount', internalType: 'uint256', type: 'uint256' }],
    name: 'addCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [
    { name: 'owner', internalType: 'address', type: 'address' },
    { name: 'spender', internalType: 'address', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [
    { name: 'spender', internalType: 'address', type: 'address' },
    { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_orderId', internalType: 'bytes32', type: 'bytes32' }],
    name: 'cancelOrder',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [],
    name: 'collateralToken',
    outputs: [{ name: '', internalType: 'contract IERC20', type: 'address' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'collectedFeesBalance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [
    { name: '_price', internalType: 'uint256', type: 'uint256' },
    { name: '_quantity', internalType: 'int256', type: 'int256' },
    ],
    name: 'createOrder',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_amount', internalType: 'uint256', type: 'uint256' }],
    name: 'depositReservePool',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [],
    name: 'getBestAskPrice',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'getBestBidPrice',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_user', internalType: 'address', type: 'address' }],
    name: 'getMaintenanceMargin',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'getMarketPrice',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_user', internalType: 'address', type: 'address' }],
    name: 'getNetPositionSize',
    outputs: [{ name: 'netQuantity', internalType: 'int256', type: 'int256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_orderId', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getOrder',
    outputs: [
    {
        name: '',
        internalType: 'struct PerpsSimple.Order',
        type: 'tuple',
        components: [
        { name: 'participant', internalType: 'address', type: 'address' },
        { name: 'price', internalType: 'uint256', type: 'uint256' },
        { name: 'quantity', internalType: 'int256', type: 'int256' },
        { name: 'createdAt', internalType: 'uint256', type: 'uint256' },
        ],
    },
    ],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_maxLevels', internalType: 'uint256', type: 'uint256' }],
    name: 'getOrderBookPrices',
    outputs: [
    { name: 'bidPrices', internalType: 'uint256[]', type: 'uint256[]' },
    { name: 'askPrices', internalType: 'uint256[]', type: 'uint256[]' },
    ],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [
    { name: '_price', internalType: 'uint256', type: 'uint256' },
    { name: '_isBid', internalType: 'bool', type: 'bool' },
    ],
    name: 'getQuantityAtPrice',
    outputs: [
    { name: 'totalQuantity', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_user', internalType: 'address', type: 'address' }],
    name: 'getRequiredMargin',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_user', internalType: 'address', type: 'address' }],
    name: 'getUnrealizedPnl',
    outputs: [{ name: '', internalType: 'int256', type: 'int256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_user', internalType: 'address', type: 'address' }],
    name: 'getUserOrders',
    outputs: [{ name: '', internalType: 'bytes32[]', type: 'bytes32[]' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_user', internalType: 'address', type: 'address' }],
    name: 'getUserPosition',
    outputs: [
    {
        name: '',
        internalType: 'struct PerpsSimple.Position',
        type: 'tuple',
        components: [
        { name: 'netQuantity', internalType: 'int256', type: 'int256' },
        {
            name: 'aggregatedEntryPrice',
            internalType: 'uint256',
            type: 'uint256',
        },
        ],
    },
    ],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'getUsersWithPositions',
    outputs: [{ name: '', internalType: 'address[]', type: 'address[]' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [
    {
        name: '_collateralToken',
        internalType: 'contract IERC20Metadata',
        type: 'address',
    },
    {
        name: '_priceOracle',
        internalType: 'contract AggregatorV3Interface',
        type: 'address',
    },
    { name: '_marginPercent', internalType: 'uint8', type: 'uint8' },
    {
        name: '_maintenanceMarginPercent',
        internalType: 'uint8',
        type: 'uint8',
    },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [{ name: '_user', internalType: 'address', type: 'address' }],
    name: 'isLiquidatable',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_user', internalType: 'address', type: 'address' }],
    name: 'liquidate',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [],
    name: 'liquidationFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'maintenanceMarginPercent',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'marginPercent',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'minimumPriceIncrement',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'orderFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'priceOracle',
    outputs: [
    {
        name: '',
        internalType: 'contract AggregatorV3Interface',
        type: 'address',
    },
    ],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [{ name: '_amount', internalType: 'uint256', type: 'uint256' }],
    name: 'removeCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [],
    name: 'reservePoolBalance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [
    { name: '_liquidationFee', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'setLiquidationFee',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [
    {
        name: '_maintenanceMarginPercent',
        internalType: 'uint8',
        type: 'uint8',
    },
    ],
    name: 'setMaintenanceMarginPercent',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [{ name: '_marginPercent', internalType: 'uint8', type: 'uint8' }],
    name: 'setMarginPercent',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [
    {
        name: '_oracle',
        internalType: 'contract AggregatorV3Interface',
        type: 'address',
    },
    ],
    name: 'setOracle',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [{ name: '_orderFee', internalType: 'uint256', type: 'uint256' }],
    name: 'setOrderFee',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [
    { name: 'to', internalType: 'address', type: 'address' },
    { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [
    { name: 'from', internalType: 'address', type: 'address' },
    { name: 'to', internalType: 'address', type: 'address' },
    { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [
    { name: 'newImplementation', internalType: 'address', type: 'address' },
    { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
},
{
    type: 'function',
    inputs: [],
    name: 'withdrawFees',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [{ name: '_amount', internalType: 'uint256', type: 'uint256' }],
    name: 'withdrawReservePool',
    outputs: [],
    stateMutability: 'nonpayable',
},
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// PriceOracleMock
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const priceOracleMockAbi = [
{
    type: 'constructor',
    inputs: [
    { name: 'initialPrice', internalType: 'int256', type: 'int256' },
    { name: 'decimals_', internalType: 'uint8', type: 'uint8' },
    ],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'description',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'freezeTimestamp',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [{ name: '', internalType: 'uint80', type: 'uint80' }],
    name: 'getRoundData',
    outputs: [
    { name: 'roundId', internalType: 'uint80', type: 'uint80' },
    { name: 'answer', internalType: 'int256', type: 'int256' },
    { name: 'startedAt', internalType: 'uint256', type: 'uint256' },
    { name: 'updatedAt', internalType: 'uint256', type: 'uint256' },
    { name: 'answeredInRound', internalType: 'uint80', type: 'uint80' },
    ],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'latestRoundData',
    outputs: [
    { name: 'roundId', internalType: 'uint80', type: 'uint80' },
    { name: 'answer', internalType: 'int256', type: 'int256' },
    { name: 'startedAt', internalType: 'uint256', type: 'uint256' },
    { name: 'updatedAt', internalType: 'uint256', type: 'uint256' },
    { name: 'answeredInRound', internalType: 'uint80', type: 'uint80' },
    ],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [
    { name: 'price', internalType: 'int256', type: 'int256' },
    { name: 'decimals_', internalType: 'uint8', type: 'uint8' },
    ],
    name: 'setPrice',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [],
    name: 'unfreezeTimestamp',
    outputs: [],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [],
    name: 'version',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'pure',
},
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// USDCMock
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const usdcMockAbi = [
{ type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
{
    type: 'error',
    inputs: [
    { name: 'spender', internalType: 'address', type: 'address' },
    { name: 'allowance', internalType: 'uint256', type: 'uint256' },
    { name: 'needed', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'ERC20InsufficientAllowance',
},
{
    type: 'error',
    inputs: [
    { name: 'sender', internalType: 'address', type: 'address' },
    { name: 'balance', internalType: 'uint256', type: 'uint256' },
    { name: 'needed', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'ERC20InsufficientBalance',
},
{
    type: 'error',
    inputs: [{ name: 'approver', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidApprover',
},
{
    type: 'error',
    inputs: [{ name: 'receiver', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidReceiver',
},
{
    type: 'error',
    inputs: [{ name: 'sender', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidSender',
},
{
    type: 'error',
    inputs: [{ name: 'spender', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidSpender',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
    },
    {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    ],
    name: 'Approval',
},
{
    type: 'event',
    anonymous: false,
    inputs: [
    { name: 'from', internalType: 'address', type: 'address', indexed: true },
    { name: 'to', internalType: 'address', type: 'address', indexed: true },
    {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
    },
    ],
    name: 'Transfer',
},
{
    type: 'function',
    inputs: [
    { name: 'owner', internalType: 'address', type: 'address' },
    { name: 'spender', internalType: 'address', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [
    { name: 'spender', internalType: 'address', type: 'address' },
    { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'pure',
},
{
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
},
{
    type: 'function',
    inputs: [
    { name: 'to', internalType: 'address', type: 'address' },
    { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
},
{
    type: 'function',
    inputs: [
    { name: 'from', internalType: 'address', type: 'address' },
    { name: 'to', internalType: 'address', type: 'address' },
    { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
},
] as const