/**
 * AUTO-GENERATED by vite-plugin-seed-meta — DO NOT EDIT MANUALLY.
 *
 * Pre-computed latest timestamps (microseconds) for each seed file.
 * Used at runtime to decide whether a seed bundle is still fresh enough to
 * warrant the network cost of loading it.  When the latest entry is older than
 * 30 days the import is skipped entirely.
 */

export const SEED_LATEST_TIMESTAMPS = {
  btcUsds: 1_785_248_343_000_000,
  btcUsdCandlesHour: 1_785_243_600_000_000,
  btcUsdCandlesDay: 1_785_110_400_000_000,
  hashpriceUsds: 1_785_248_445_000_000,
  hashpriceUsdCandlesHour: 1_785_243_600_000_000,
  hashpriceUsdCandlesDay: 1_785_110_400_000_000,
} as const;
