/// <reference types="node" />

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import type { Plugin } from "vite";

const SEED_DIR = resolve(__dirname, "src/seed");
const META_PATH = resolve(SEED_DIR, "meta.ts");

const SEED_FILES = [
  { file: "btcUsds.json", key: "btcUsds" },
  { file: "btcUsdCandles-hour.json", key: "btcUsdCandlesHour" },
  { file: "btcUsdCandles-day.json", key: "btcUsdCandlesDay" },
  { file: "hashpriceUsds.json", key: "hashpriceUsds" },
  { file: "hashpriceUsdCandles-hour.json", key: "hashpriceUsdCandlesHour" },
  { file: "hashpriceUsdCandles-day.json", key: "hashpriceUsdCandlesDay" },
] as const;

function generateMeta(): void {
  const entries: [string, number][] = [];

  for (const { file, key } of SEED_FILES) {
    const raw = readFileSync(resolve(SEED_DIR, file), "utf-8");
    const data = JSON.parse(raw) as { timestamp: string | number }[];
    const latest = Math.max(...data.map((item) => Number(item.timestamp)));
    entries.push([key, latest]);
  }

  const lines = [
    "/**",
    " * AUTO-GENERATED by vite-plugin-seed-meta — DO NOT EDIT MANUALLY.",
    " *",
    " * Pre-computed latest timestamps (microseconds) for each seed file.",
    " * Used at runtime to decide whether a seed bundle is still fresh enough to",
    " * warrant the network cost of loading it.  When the latest entry is older than",
    " * 30 days the import is skipped entirely.",
    " */",
    "",
    "export const SEED_LATEST_TIMESTAMPS = {",
    ...entries.map(([key, ts]) => `  ${key}: ${ts.toLocaleString("en-US").replace(/,/g, "_")},`),
    "} as const;",
    "",
  ];

  writeFileSync(META_PATH, lines.join("\n"), "utf-8");
  console.log("[seed-meta] regenerated meta.ts");
}

/** Vite plugin that regenerates seed meta on every build/dev start. */
export function seedMetaPlugin(): Plugin {
  return {
    name: "seed-meta",
    buildStart() {
      generateMeta();
    },
  };
}
